// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyuyrwrylchkkyilyvlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5dXlyd3J5bGNoa2t5aWx5dmxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MDc0MTYsImV4cCI6MjA2NzM4MzQxNn0.i2OVpMRdvNVByodg99c0k0VjPPZu9ha3lvZzJAvXgQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});