// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Temporarily hardcode the values to bypass env variable issues
const SUPABASE_URL = 'https://zyuyrwrylchkkyilyvlh.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9'; // Your anon key

// Fallback to env variables if they exist
const finalUrl = import.meta.env.VITE_SUPABASE_URL || SUPABASE_URL;
const finalKey = import.meta.env.VITE_SUPABASE_ANON_KEY || SUPABASE_PUBLISHABLE_KEY;

if (!finalUrl || !finalKey || finalKey === 'your_actual_anon_key_here') {
  throw new Error('Missing Supabase environment variables. Please check your .env file or hardcoded values.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(finalUrl, finalKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});